# Generated by Django 3.1.11 on 2021-05-15 12:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='Покупатель')),
                ('item', models.CharField(max_length=100, verbose_name='Предмет')),
                ('total', models.IntegerField()),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FileCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.models.file_directory_path, verbose_name='Ваш файл')),
            ],
        ),
    ]
