# Generated by Django 3.1.11 on 2021-05-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='spent_money',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего потрачено средств'),
        ),
        migrations.AlterField(
            model_name='item',
            name='total',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='itemandcustomer',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='purchasedate',
            name='date',
            field=models.DateTimeField(verbose_name='Дата сделки'),
        ),
    ]
