version: "3.7"


services:
  sibdb:
    image: postgres:10
    environment:
      POSTGRES_DB: sibdev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zinnurik123321

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: sibdb
      DB_PASSWORD: zinnurik123321
    ports:
      - 8000:8000
    depends_on:
       - sibdb
